version: '3.9'
services:
  server:
    restart: on-failure
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  
  client:
    restart: on-failure
    build: ./client
    ports:
      - '5173:5173'
    depends_on:
      - server